obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_hotplug.o
obj-$(CONFIG_HIMA_HOTPLUG) += hima_hotplug.o
obj-$(CONFIG_MSM_HOTPLUG) += msm_hotplug.o
obj-$(CONFIG_BLU_PLUG)				+= blu_plug.o
